version: '3.8'

services:
  pg_db:
    container_name: pg_db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=weather
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  server:
    container_name: server
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - pg_db
    environment:
      - DATABASE_URL=${DATABASE_URL} 
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_USER=${EMAIL_USER}
    env_file:
      - ./server/.env
    
      
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000



volumes:
  postgres_data:
